/* Profile content — sourced from anandtopu/anandtopu README. Counts are truthful. */
window.PROFILE = {
  name: "Anand Topu",
  handle: "anandtopu",
  role: "Solution Architect · AI Systems · Distributed Platforms",
  company: "EPAM Systems",
  location: "Frisco, Texas",
  links: {
    linkedin: "https://www.linkedin.com/in/anandtopu/",
    credly: "https://www.credly.com/users/anand-topu/badges",
    github: "https://github.com/anandtopu",
  },
  lede: "Solution Architect at EPAM focused on AI-powered systems, agentic architectures, and distributed platform engineering — shipping production-grade AI platforms that bridge ML research and real-world enterprise deployments.",
  signals: [
    "multi-agent LLM systems",
    "production RAG",
    "MCP servers",
    "A2A protocol",
    "AI observability",
  ],
  focus: [
    { k: "production_rag", v: "multi-tenancy · hallucination detection · cost budgets · audit" },
    { k: "agent_orchestration", v: "LangGraph · Anthropic Agent SDK · A2A" },
    { k: "mcp_servers", v: "expose tools + data to agents safely" },
    { k: "ai_observability", v: "tracing · evals · monitoring at scale" },
    { k: "platform", v: "OpenShift / Kubernetes-native AI deploys" },
  ],
  heroStats: [
    { v: 25, suffix: "+", k: "verified certifications" },
    { v: 3, suffix: "", k: "clouds — GCP · AWS · Azure" },
    { v: 13, suffix: "", k: "featured repositories" },
    { v: 30, suffix: "+", k: "GCP skill badges" },
  ],
  stack: [
    { label: "AI / ML", items: ["LangChain","LangGraph","PydanticAI","Anthropic SDK","MCP","A2A","Ollama","OpenAI","ChromaDB","pgvector","Hugging Face"] },
    { label: "Backend", items: ["Python","Go","FastAPI","Celery","Temporal","TypeScript"] },
    { label: "Data / Msg", items: ["PostgreSQL","MongoDB","Redis","Cassandra","MinIO"] },
    { label: "Infra / Cloud", items: ["Docker","Kubernetes","OpenShift","Helm","ArgoCD","Terraform","GCP"] },
    { label: "Frontend", items: ["React","Vite","Tailwind"] },
  ],
  projects: [
    { id:"sentinelrag", cat:"ai", feat:true, icon:"shield", name:"SentinelRAG",
      tagline:"Multi-tenant, RBAC-aware, evaluation-driven enterprise RAG",
      desc:"Production-shaped RAG with pgvector hybrid retrieval, layered hallucination detection, immutable audit, and per-tenant cost budgets. Multi-cloud Terraform, Helm + ArgoCD, k6 + Chaos Mesh resilience tests, and 30 ADRs explaining every non-obvious decision.",
      tags:["Python","FastAPI","Temporal","PostgreSQL","pgvector","Redis","Helm","ArgoCD","Terraform","Kubernetes"],
      url:"https://github.com/anandtopu/sentinal-rag" },
    { id:"qainsight", cat:"ai", icon:"flask", name:"QA Insight AI",
      tagline:"360° AI-powered software testing intelligence",
      desc:"Ingests test results from 50+ frameworks, correlates failures using a LangChain ReAct multi-agent network, and delivers structured root-cause analysis. Air-gapped LLM support via Ollama; OpenShift/Kubernetes native.",
      tags:["Python","FastAPI","LangChain","LangGraph","PostgreSQL","MongoDB","ChromaDB","React","Kubernetes"],
      url:"https://github.com/anandtopu/qainsight-ai" },
    { id:"testlookup", cat:"ai", icon:"search", name:"TestLookup",
      tagline:"Local-first test failure intelligence for CI & QA",
      desc:"Turns raw automated test results (JUnit, pytest, TestNG, Allure, Cypress, Playwright…) into actionable failure intelligence and release-risk signals — GO / CONDITIONAL_GO / NO_GO. Local-first, offline-capable, exposed via API / CLI / UI / MCP.",
      tags:["Python","TypeScript","MCP","Ollama","Docker Compose","Kubernetes"],
      url:"https://github.com/anandtopu/testlookup" },
    { id:"agentmemory", cat:"ai", icon:"brain", name:"AgentMemory",
      tagline:"Guides & deep dives on memory-augmented agents",
      desc:"A growing collection of practical articles, code examples, and Mermaid diagrams on building production-grade agent memory — short-term, long-term, episodic, and semantic.",
      tags:["Mermaid","Documentation","AI Agents"],
      url:"https://github.com/anandtopu/AgentMemory" },
    { id:"buildingai", cat:"ai", icon:"robot", name:"Building AI Agents",
      tagline:"Designing agentic systems with LangChain",
      desc:"Reference patterns for tool-use, planning, multi-step reasoning, and agent composition.",
      tags:["Python","LangChain","LangGraph"],
      url:"https://github.com/anandtopu/BuildingAIAgents" },
    { id:"pydanticai", cat:"ai", icon:"code", name:"PydanticAI Practice",
      tagline:"Runnable tutorial for learning PydanticAI",
      desc:"Hands-on examples covering type-safe agents, dependency injection, structured outputs, and streaming.",
      tags:["Python","PydanticAI"],
      url:"https://github.com/anandtopu/pydantic-ai-practice" },
    { id:"pyagents", cat:"ai", icon:"terminal", name:"Python AI Agents Demo",
      tagline:"Reference implementation of agentic patterns",
      desc:"Hands-on CLI demonstrating tool use, multi-step reasoning, and ReAct loops.",
      tags:["Python","LangChain","AI Agents","CLI"],
      url:"https://github.com/anandtopu/python-ai-agents-demo" },
    { id:"scheduler", cat:"dist", icon:"calendar", name:"Distributed Job Scheduler",
      tagline:"Production-grade distributed job scheduling",
      desc:"High-throughput workloads with fault tolerance, distributed locking, and horizontal scaling.",
      tags:["Python","FastAPI","Cassandra","Redis"],
      url:"https://github.com/anandtopu/job-scheduler" },
    { id:"dcache", cat:"dist", icon:"layers", name:"Distributed Cache (Go)",
      tagline:"Distributed cache implementation in Go",
      desc:"Polyglot exploration of consistent hashing, replication, and failure handling.",
      tags:["Go","Distributed Systems"],
      url:"https://github.com/anandtopu/Distributed-Cache" },
    { id:"crawler", cat:"dist", icon:"globe", name:"Web Crawler",
      tagline:"Scalable web crawler with a management UI",
      desc:"Internet-scale crawler with a TypeScript web UI for job management, monitoring, and control.",
      tags:["TypeScript","System Design","Distributed Systems"],
      url:"https://github.com/anandtopu/web-crawler" },
    { id:"briefly", cat:"dist", icon:"link", name:"Briefly — URL Shortener",
      tagline:"URL shortening service with analytics",
      desc:"Production-ready URL shortener with click analytics, built as a system-design reference implementation.",
      tags:["Python","FastAPI","System Design"],
      url:"https://github.com/anandtopu/Briefly" },
    { id:"ratelimiter", cat:"dist", icon:"gauge", name:"Distributed Rate Limiter",
      tagline:"High-performance distributed rate limiting",
      desc:"Token-bucket and sliding-window algorithms for distributed API gateways.",
      tags:["Python","Redis","Distributed Systems"],
      url:"https://github.com/anandtopu/rate-limiter" },
    { id:"payment", cat:"dist", icon:"card", name:"Payment System",
      tagline:"Payment system demo application",
      desc:"System-design reference for transactional flows, idempotency, and reconciliation.",
      tags:["TypeScript","System Design"],
      url:"https://github.com/anandtopu/payment-system" },
  ],
  learning: [
    { name:"AIEngineer", sub:"Roadmap to AI Engineer interview prep", url:"https://github.com/anandtopu/AIEngineer" },
    { name:"Vector Databases", sub:"Embeddings, indexes & retrieval", url:"https://github.com/anandtopu/vector-databases" },
    { name:"Redis Practice", sub:"Real-world Redis patterns", url:"https://github.com/anandtopu/redis-practice" },
    { name:"100 Days of ML", sub:"ML fundamentals practice", url:"https://github.com/anandtopu/100DaysOfMachineLearning" },
    { name:"Web UI Automation", sub:"Automation toolkit", url:"https://github.com/anandtopu/web-ui-automation" },
    { name:"NeetCode Submissions", sub:"Algorithmic problem solving", url:"https://github.com/anandtopu/neetcode-submissions" },
  ],
  certProviders: [
    { id:"gcp", name:"Google Cloud", color:"var(--gcp)" },
    { id:"aws", name:"AWS", color:"var(--aws)" },
    { id:"azure", name:"Azure", color:"var(--azure)" },
    { id:"oreilly", name:"O'Reilly", color:"var(--oreilly)" },
    { id:"ibm", name:"IBM", color:"var(--ibm)" },
  ],
  certs: [
    { p:"gcp", n:"Professional Cloud Architect", e:"Expires Dec 2026" },
    { p:"gcp", n:"Professional ML Engineer", e:"Expires Feb 2028" },
    { p:"gcp", n:"Generative AI Leader", e:"Expires Feb 2029" },
    { p:"gcp", n:"Professional Data Engineer", e:"Expires Dec 2027" },
    { p:"gcp", n:"Professional Cloud DevOps Engineer", e:"Expires Feb 2028" },
    { p:"gcp", n:"Professional Cloud Network Engineer", e:"Expires Feb 2028" },
    { p:"gcp", n:"Professional Cloud Database Engineer", e:"Expires Feb 2028" },
    { p:"gcp", n:"Associate Cloud Engineer", e:"Expires Oct 2028" },
    { p:"gcp", n:"Associate Data Practitioner", e:"Expires Dec 2027" },
    { p:"aws", n:"Solutions Architect Associate", e:"Expires Nov 2027" },
    { p:"aws", n:"ML Engineer Associate", e:"Expires Oct 2027" },
    { p:"aws", n:"Data Engineer Associate", e:"Expires Oct 2027" },
    { p:"aws", n:"AI Practitioner", e:"Expires Oct 2027" },
    { p:"aws", n:"Developer Associate", e:"Expires Aug 2028" },
    { p:"aws", n:"Cloud Practitioner", e:"Expires Aug 2028" },
    { p:"aws", n:"Well-Architected Proficient", e:"Issued Jan 2026" },
    { p:"aws", n:"GenAI Essentials Partner", e:"Issued Nov 2024" },
    { p:"azure", n:"Azure Fundamentals (AZ-900)", e:"Issued Jan 2022" },
    { p:"azure", n:"Azure AI Fundamentals (AI-900)", e:"Issued Jan 2022" },
    { p:"azure", n:"Azure Data Fundamentals (DP-900)", e:"Issued Jan 2022" },
    { p:"oreilly", n:"AI Agents Core Components", e:"Issued Mar 2026" },
    { p:"oreilly", n:"Getting Started with LangGraph", e:"Issued Feb 2025" },
    { p:"oreilly", n:"Microservices Data Decomposition", e:"Issued Jan 2025" },
    { p:"oreilly", n:"AWS S3 Hands-on", e:"Issued Feb 2025" },
    { p:"ibm", n:"Enterprise Design Thinking Practitioner", e:"Issued Mar 2025" },
  ],
  skillBadges: [
    ["Build & Deploy ML Solutions on Vertex AI","Jan 2025"],
    ["Build a Data Warehouse with BigQuery","Mar 2025"],
    ["Engineer Data for Predictive Modeling — BigQuery ML","Mar 2025"],
    ["Prepare Data for ML APIs on Google Cloud","Mar 2025"],
    ["Create & Manage Cloud Spanner Instances","Mar 2025"],
    ["Implement DevOps Workflows in Google Cloud","Mar 2025"],
    ["Monitor & Log with Cloud Operations Suite","Mar 2025"],
    ["Develop Serverless Apps with Firebase","Jan 2025"],
    ["Develop Serverless Applications on Cloud Run","Dec 2024"],
    ["Share Data Using Google Data Cloud","Dec 2024"],
    ["Protect Sensitive Data with DLP","Nov 2024"],
    ["Implement Cloud Security Fundamentals","Nov 2024"],
    ["Create & Manage Bigtable Instances","Nov 2024"],
    ["Automate Data Capture with Document AI","Nov 2024"],
    ["Build a Data Mesh with Dataplex","Nov 2024"],
    ["Networking Fundamentals on Google Cloud","Nov 2024"],
    ["Deploy Kubernetes Applications on GCP","Nov 2024"],
    ["Build Infrastructure with Terraform on GCP","Nov 2024"],
    ["Implement Load Balancing on Compute Engine","Nov 2024"],
    ["Text Prompt Engineering Techniques","Nov 2024"],
  ],
  skills: [
    { n:"Cloud Computing", c:22 },
    { n:"Cloud Storage", c:14 },
    { n:"Amazon Web Services", c:13 },
    { n:"Google Cloud Platform", c:11 },
    { n:"Machine Learning", c:11 },
    { n:"Artificial Intelligence", c:8 },
    { n:"BigQuery", c:8 },
    { n:"Identity & Access Mgmt", c:8 },
    { n:"Cloud Security", c:5 },
    { n:"Compute Engine", c:5 },
    { n:"Data Ingestion", c:5 },
    { n:"Cloud Architecture", c:4 },
  ],
  languages: [
    { n:"Python", pct:52, c:"#3776AB" },
    { n:"TypeScript", pct:24, c:"#3178C6" },
    { n:"Go", pct:11, c:"#00ADD8" },
    { n:"Shell / HCL", pct:8, c:"#89e051" },
    { n:"Other", pct:5, c:"#586573" },
  ],
};
